### ISSUE TITLE
案例 drivaernetplusplus 在Nvidia A100平台训练报错，CUDNN error(3000), CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by yuchunliu-metax** [PaddlePaddle/PaddleScience#1132]
### bug 描述 bug description

软件版本：paddle：2.6.2 , PaddleScience：commit 44cd7a0ee91691d25e08346efdfc2d7f4ed36d7d
测试案例：[/opt/PaddleScience/examples/drivaernetplusplus](https://paddlescience-docs.readthedocs.io/zh-cn/latest/zh/examples/drivaernetplusplus/)
测试环境：NVIDIA A100-PCIE-40GB

训练报错：与  https://github.com/PaddlePaddle/Paddle/issues/50853 CUDNN中问题相似
_train cmd:_

`python3 ./drivaernetplusplus.py`

_error log:_
```
(paddle2.6_ppsci_py310) /opt/PaddleScience/examples/drivaernetplusplus# python3 ./drivaernetplusplus.py
W0406 12:47:40.342653   665 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.5, Runtime API Version: 12.0
W0406 12:47:40.343582   665 gpu_resources.cc:164] device: 0, cuDNN Version: 9.7.
[2025/04/06 12:47:40] ppsci MESSAGE: 'shuffle' and 'drop_last' are both set to False in default as sampler config is not specified.
[2025/04/06 12:47:40] ppsci MESSAGE: 'shuffle' and 'drop_last' are both set to False in default as sampler config is not specified.
[2025/04/06 12:47:41] ppsci WARNING: The argument: 'lr_scheduler' now automatically retrieves from 'optimizer._learning_rate' when 'optimizer' is given, so it is recommended to remove it from the Solver's initialization arguments.
[2025/04/06 12:47:41] ppsci INFO: Using paddlepaddle 2.6.2 on device Place(gpu:0)
[2025/04/06 12:47:41] ppsci MESSAGE: Set to_static=False for computational optimization.
python3 ./drivaernetplusplus.pyError executing job with overrides: []
Traceback (most recent call last):
  File "/opt/PaddleScience/examples/drivaernetplusplus/./drivaernetplusplus.py", line 192, in main
    train(cfg)
  File "/opt/PaddleScience/examples/drivaernetplusplus/./drivaernetplusplus.py", line 131, in train
    solver.train()
  File "/opt/PaddleScience/ppsci/solver/solver.py", line 572, in train
    self.train_epoch_func(self, epoch_id, self.log_freq)
  File "/opt/PaddleScience/ppsci/solver/train.py", line 117, in train_epoch_func
    losses_all, losses_constraint = solver.forward_helper.train_forward(
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 494, in __call__
    return self._call_dygraph_function(*args, **kwargs)
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 527, in _call_dygraph_function
    return self.dygraph_function(*args, **kwargs)
  File "/opt/PaddleScience/ppsci/utils/expression.py", line 96, in train_forward
    output_dict = model(input_dicts[i])
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/PaddleScience/ppsci/arch/regpointnet.py", line 125, in forward
    shortcut = self.bn_shortcut(self.conv_shortcut(x_processed))
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/nn/layer/conv.py", line 375, in forward
    out = F.conv1d(
  File "/opt/anaconda3/envs/paddle2.6_ppsci_py310/lib/python3.10/site-packages/paddle/nn/functional/conv.py", line 464, in conv1d
    out = _C_ops.conv2d(
OSError: (External) CUDNN error(3000), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: Please search for the error code(3000) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cudnn_desc.h:162)


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

**Comment by HydrogenSulfate** [comment]
印象里是输入到conv2d的点数过多导致的，可以尝试把TRAIN.num_points调低点试试，案例中所给的配置是原论文的大显存配置，40G可能跑不起来

**Comment by yuchunliu-metax** [comment]
> 印象里是输入到conv2d的点数过多导致的，可以尝试把TRAIN.num_points调低点试试，案例中所给的配置是原论文的大显存配置，40G可能跑不起来

减少points数量，可以正常训练，不会报错。
